### PR TITLE
#46 Theme Settings: Custom Comment Contrast

### PR DESCRIPTION
**Pull request by arcticicestudio**
This PR implements theme settings and various improvements to the build- and development workflow.
ghi-46-scrot-syntax-theme-settings

The initial implementation provides a setting to increase the contrast for comments by percentage.
ghi-46-scrot-syntax-theme-setting-custom-comment-contrast
ghi-46-scrot-comments-contrast-default
The default value is `0` which uses the default Nord color assignment while the maximum value is `20`.

Example with an increased comment contrast value of `15` (%):
ghi-46-scrot-syntax-theme-setting-custom-comment-contrast-value
ghi-46-scrot-comments-contrast-customized

Unfortunately Atom does currently not support modifications of LESSCSS theme variables through configurations so a workaround has been implemented which stores LESSCSS variables in the index-imported `styles/theme-settings-store.less` file to override the default LESSCSS variables defined in the `styles/syntax-variables.less` file.
Please see [atom/atom PR #4153](https://github.com/atom/atom/pull/4153) and [atom/atom #5735](https://github.com/atom/atom/issues/5735) for more information about the current limitations.

---

**Solves issue** #46 
/cc @ascarter @mattfysh @adrian5

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Alright, I'll have to take care of the builds errors at another time. Everything works fine on my local system (Arch Linux), but the builds on Travis Linux are failing with a JavaScript syntax error which can only be due to the Babel ES6 code (lambda function expression).
Curiously the Travis OSX builds running just fine without any error 😕

**Comment by ascarter** [comment]
+1. This works great. Accessibility percentage adjustments seem like a nice way to expose this. This worked well for me on my machine. Thanks!

**Comment by ascarter** [comment]
And FYI - I tested on my iMac and MacBook Pro both running latest Sierra and latest stable Atom.

**Comment by arcticicestudio** [comment]
I finally fixed all Travis CI builds in all environments. The `linux` builds are unfortunately based on Ubuntu which only comes with the pre-installed (outdated) Node version `0.10.x`.
The specs and Atom tests using a bundled Node runtime, but the `gulp lint` command uses the locally installed Node.
Now using [nvm](https://github.com/creationix/nvm) to install the necessary Node version Atom is bundled with and runs the  `gulp lint` command before the actual script Atom CI script. Afterwards the `nvm deactivate` enures that the bundled Node version does not collide with the locally installed Node version.

Anyway, I'll merge this PR into `develop` and prepare a new APM package release.

**Pull request merged**
