### PR TITLE
Fix Closing PHP Tag ? Incorrectly Highlighted

### LINKED ISSUE #54: Closing PHP Tag ? Incorrectly Highlighted
The ? inherits `.syntax--source` coloring. It should use the `.syntax--punctuation.syntax--section.syntax--embedded` coloring. It is the same whether on its own line or in line.

image

Atom Version: 1.12.0

### PR DESCRIPTION
**Pull request by amayer5125**
Fixes #54

### CODE REVIEW

**Comment by amayer5125** [comment]
I don't believe this has anything to do with atom changing as other themes do not have the same problem.

The problem maybe that we are setting too many colors. For example if you remove [line 16](https://github.com/arcticicestudio/nord-atom-syntax/blob/master/styles/syntax.less#L16) and [line 185](https://github.com/arcticicestudio/nord-atom-syntax/blob/master/styles/syntax.less#L185) from syntax.less everything looks good.

I checked a couple languages after doing that and everything looked good. Is there a specific reason these were added here? If an element does not have a better scope it will be set by [line 13](https://github.com/arcticicestudio/nord-atom-syntax/blob/master/styles/editor.less#L13) of editor.less which is what most other themes do.

Maybe we revert #53 in favor of removing these color definitions? If you would like me to put that together I can.

**Comment by amayer5125** [comment]
I added this to my custom style sheet and then looked through a project with 44 different languages in it and everything looked fine.
```less
.syntax--source, .syntax--meta {
  color: unset;
}
```

**Comment by amayer5125** [comment]
@arcticicestudio do you think my new solution would work? I can amend this request if it seems like a good idea.

**Comment by arcticicestudio** [comment]
Sounds like a great improvement! I've planned to refactor the syntax- and UI Atom themes to clean them up and I think this might be good start to prevent issues like #53 and #54.

**Comment by amayer5125** [comment]
I made the updates I was talking about.
Should I change this merge request to merge into release/0.10.0?

**Comment by arcticicestudio** [comment]
Maybe a new PR would be better so I can close this one and mark it to be superseded by the the new PR including the specific issues. If the changes also fix #52 I'll revert the merge.

You can use the `develop` branch for the new PR, I'll organize the versions later on and change it if it better fits in version 0.10.0.

**Comment by amayer5125** [comment]
Ok. I will do that.

**Comment by arcticicestudio** [comment]
> Superseded by #56

**Pull request closed without merging**
